sudo: true

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

before_install:
  # Install GCC 6 if on OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   brew update                ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   brew tap homebrew/versions ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   brew install gcc6          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   brew install gnu-indent    ; fi
  # Set GCC 6 as Default on both Ubuntu and OSX
  - alias gcc=$(which gcc-6)
  - which clang
  - clang --version
  # Install latest version of clang, clang++, and llvm-symbolizer and add them to beginning of PATH. Needed for fuzzing.
  - (.travis/install_clang.sh `pwd`/clang-download `pwd`/clang-latest $TRAVIS_OS_NAME) && export PATH=`pwd`/clang-latest/bin:$PATH

  # Install llvm 4.0
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty main" -y; sudo apt-get update; wget -O - http://apt.llvm.org/llvm-snapshot.gpg.key|sudo apt-key add -; sudo apt-get -f install llvm-4.0 -y; fi

  # Install SAW on Linux only 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl http://saw.galois.com/builds/nightly/saw-0.2-2016-07-22-Ubuntu14.04-64.tar.gz > saw.tar.gz; tar -xzvf saw.tar.gz; fi
  - export PATH=$PATH:$PWD/saw-0.2-2016-07-22-Ubuntu14.04-64/bin

install:
  - .travis/install_openssl.sh `pwd`/libcrypto-build `pwd`/libcrypto-root $TRAVIS_OS_NAME > /dev/null
  # Install python linked with our compiled Openssl for integration tests
  - sudo .travis/install_python.sh `pwd`/libcrypto-root > /dev/null
  # Install prlimit to set the memlock limit to unlimited for this process
  - (test "$TRAVIS_OS_NAME" = "linux" && sudo .travis/install_prlimit.sh $PWD/.travis && sudo .travis/prlimit --pid "$$" --memlock=unlimited:unlimited) || true
 

script:
  - (test "$TRAVIS_OS_NAME" = "linux" && make -j8) || true
  # Build and run unit tests with scan-build for osx. scan-build bundle isn't available for linux
  - (test "$TRAVIS_OS_NAME" = "osx" && scan-build --status-bugs -o /tmp/scan-build make -j8; STATUS=$?; test $STATUS -ne 0 && cat /tmp/scan-build/*/*; exit $STATUS) || true
  - make integration
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then make saw; fi 
