sudo: true
language: c

addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
      packages:
        - gcc-6
        - g++-6
        - indent
        - cppcheck

osx_image: xcode8

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

env:
  - BUILD_S2N=true TESTS=unit
  - LATEST_CLANG=true TESTS=fuzz
  - TESTS=sawHMAC

matrix:
  exclude:
  - compiler: gcc
    env: TESTS=sawHMAC
  - os: osx
    env: TESTS=sawHMAC
  - compiler: gcc
    env: LATEST_CLANG=true TESTS=fuzz

before_install:
  # Install GCC 6 if on OSX
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then   .travis/brew_install_gcc6.sh ; fi
  # Set GCC 6 as Default on both Ubuntu and OSX
  - alias gcc=$(which gcc-6)
  # Install latest version of clang, clang++, and llvm-symbolizer and add them to beginning of PATH. Needed for fuzzing.
  - if [[ "$LATEST_CLANG" == "true" ]]; then (.travis/install_clang.sh `pwd`/clang-download `pwd`/clang-latest $TRAVIS_OS_NAME) && export PATH=`pwd`/clang-latest/bin:$PATH ; fi

  # Install SAW with Z3 on Linux only 
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .travis/install_saw.sh ; fi
  - export PATH=$PATH:$PWD/saw-0.2-2016-09-22-Ubuntu14.04-64/bin:$PWD/z3

install:
  # Download and Install LibFuzzer
  - if [[ "$TESTS" == "fuzz" ]]; then .travis/install_libFuzzer.sh `pwd`/fuzz_dependencies/libFuzzer-download `pwd`/fuzz_dependencies $TRAVIS_OS_NAME ; fi
  # Download and Install Openssl
  - if [[ "$BUILD_S2N" == "true" ]]; then .travis/install_openssl.sh `pwd`/libcrypto-build `pwd`/libcrypto-root $TRAVIS_OS_NAME > /dev/null ; fi
  # Install python linked with our compiled Openssl for integration tests
  - if [[ "$BUILD_S2N" == "true" ]]; then sudo "PATH=$PATH" .travis/install_python.sh `pwd`/libcrypto-root > /dev/null ; fi
  # Install prlimit to set the memlock limit to unlimited for this process
  - if [[ "$BUILD_S2N" == "true" ]]; then (test "$TRAVIS_OS_NAME" = "linux" && sudo "PATH=$PATH" .travis/install_prlimit.sh $PWD/.travis > /dev/null && sudo .travis/prlimit --pid "$$" --memlock=unlimited:unlimited) || true ; fi
  - mkdir -p .travis/checker && .travis/install_scan-build.sh .travis/checker && export PATH=$PATH:.travis/checker/bin
  - if [[ "$BUILD_S2N' == "true" ]]; then .travis/run_cppcheck.sh ; fi

script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TESTS" == "unit" ]]; then make -j 8   ; fi
  # Build and run unit tests with scan-build for osx. scan-build bundle isn't available for linux
  - if [[ "$TRAVIS_OS_NAME" == "osx" && "$TESTS" == "unit" ]]; then   scan-build --status-bugs -o /tmp/scan-build make -j8; STATUS=$?; test $STATUS -ne 0 && cat /tmp/scan-build/*/*; exit $STATUS ; fi
  - if [[ "$TESTS" == "unit" ]]; then make integration ; fi
  - if [[ "$TESTS == "fuzz" ]]; then make clean && make fuzz fi;
  - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TESTS"== "sawHMAC"]]; then make saw; fi 