sudo: true

os:
  - osx
  - linux

compiler:
  - gcc
  - clang

install:
  - .travis/install_openssl.sh `pwd`/libcrypto-build `pwd`/libcrypto-root $TRAVIS_OS_NAME > /dev/null
  # Install python linked with our compiled Openssl for integration tests
  - .travis/install_python.sh `pwd`/libcrypto-root > /dev/null
  # Install prlimit to set the memlock limit to unlimited for this process 
  - (test "$TRAVIS_OS_NAME" = "linux" && sudo .travis/install_prlimit.sh $PWD/.travis > /dev/null && sudo .travis/prlimit --pid "$$" --memlock=unlimited:unlimited) || true

script:
  - make -j8
  - make integration
